/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicImpressumRouteImport } from './routes/_public/impressum'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ShopProductIdSplatRouteImport } from './routes/shop/product.id.$'

const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ShopProductIdSplatRoute = ShopProductIdSplatRouteImport.update({
  id: '/product/id/$',
  path: '/product/id/$',
  getParentRoute: () => ShopRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/shop': typeof ShopRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/impressum': typeof PublicImpressumRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/id/$': typeof ShopProductIdSplatRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/impressum': typeof PublicImpressumRoute
  '/': typeof PublicIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/product/id/$': typeof ShopProductIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/': typeof PublicIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/id/$': typeof ShopProductIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/about'
    | '/impressum'
    | '/shop/'
    | '/shop/product/id/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/impressum' | '/' | '/shop' | '/shop/product/id/$'
  id:
    | '__root__'
    | '/_public'
    | '/shop'
    | '/_public/about'
    | '/_public/impressum'
    | '/_public/'
    | '/shop/'
    | '/shop/product/id/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/shop/product/id/$': {
      id: '/shop/product/id/$'
      path: '/product/id/$'
      fullPath: '/shop/product/id/$'
      preLoaderRoute: typeof ShopProductIdSplatRouteImport
      parentRoute: typeof ShopRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdSplatRoute: typeof ShopProductIdSplatRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdSplatRoute: ShopProductIdSplatRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
