/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutsShopIndexRouteImport } from './routes/_layouts/shop/index'
import { Route as LayoutsShopShopRouteImport } from './routes/_layouts/shop/shop'
import { Route as LayoutsShopProductIdRouteImport } from './routes/_layouts/shop/$productId'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsShopIndexRoute = LayoutsShopIndexRouteImport.update({
  id: '/_layouts/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsShopShopRoute = LayoutsShopShopRouteImport.update({
  id: '/_layouts/shop/shop',
  path: '/shop/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsShopProductIdRoute = LayoutsShopProductIdRouteImport.update({
  id: '/_layouts/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/shop/$productId': typeof LayoutsShopProductIdRoute
  '/shop/shop': typeof LayoutsShopShopRoute
  '/shop/': typeof LayoutsShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/shop/$productId': typeof LayoutsShopProductIdRoute
  '/shop/shop': typeof LayoutsShopShopRoute
  '/shop': typeof LayoutsShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/_layouts/shop/$productId': typeof LayoutsShopProductIdRoute
  '/_layouts/shop/shop': typeof LayoutsShopShopRoute
  '/_layouts/shop/': typeof LayoutsShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impressum'
    | '/shop/$productId'
    | '/shop/shop'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impressum'
    | '/shop/$productId'
    | '/shop/shop'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impressum'
    | '/_layouts/shop/$productId'
    | '/_layouts/shop/shop'
    | '/_layouts/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpressumRoute: typeof ImpressumRoute
  LayoutsShopProductIdRoute: typeof LayoutsShopProductIdRoute
  LayoutsShopShopRoute: typeof LayoutsShopShopRoute
  LayoutsShopIndexRoute: typeof LayoutsShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layouts/shop/': {
      id: '/_layouts/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof LayoutsShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layouts/shop/shop': {
      id: '/_layouts/shop/shop'
      path: '/shop/shop'
      fullPath: '/shop/shop'
      preLoaderRoute: typeof LayoutsShopShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layouts/shop/$productId': {
      id: '/_layouts/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof LayoutsShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpressumRoute: ImpressumRoute,
  LayoutsShopProductIdRoute: LayoutsShopProductIdRoute,
  LayoutsShopShopRoute: LayoutsShopShopRoute,
  LayoutsShopIndexRoute: LayoutsShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
