/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as DashboardDetailIdRouteImport } from './routes/dashboard/detail.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/layout',
  path: '/dashboard/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDetailIdRoute = DashboardDetailIdRouteImport.update({
  id: '/dashboard/detail/$id',
  path: '/dashboard/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/products': typeof ProductsRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/detail/$id': typeof DashboardDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/products': typeof ProductsRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/detail/$id': typeof DashboardDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/products': typeof ProductsRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/detail/$id': typeof DashboardDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impressum'
    | '/products'
    | '/dashboard/$id'
    | '/dashboard/layout'
    | '/dashboard/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impressum'
    | '/products'
    | '/dashboard/$id'
    | '/dashboard/layout'
    | '/dashboard/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impressum'
    | '/products'
    | '/dashboard/$id'
    | '/dashboard/layout'
    | '/dashboard/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpressumRoute: typeof ImpressumRoute
  ProductsRoute: typeof ProductsRoute
  DashboardIdRoute: typeof DashboardIdRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardDetailIdRoute: typeof DashboardDetailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/layout': {
      id: '/dashboard/layout'
      path: '/dashboard/layout'
      fullPath: '/dashboard/layout'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/detail/$id': {
      id: '/dashboard/detail/$id'
      path: '/dashboard/detail/$id'
      fullPath: '/dashboard/detail/$id'
      preLoaderRoute: typeof DashboardDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpressumRoute: ImpressumRoute,
  ProductsRoute: ProductsRoute,
  DashboardIdRoute: DashboardIdRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardDetailIdRoute: DashboardDetailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
